### ISSUE TITLE
API error

### ISSUE THREAD

**Issue by Skadro** [kem0o/neobot#3]
After the login process, "**https://www.epicgames.com/id/api/exchange**" returns with:

```
<html lang="en"><head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /id/api/exchange</pre>


</body></html>
```

I tried "Neobot V1.0.0" and "Neobot V1.0.1", but I have the same problem with both.

Epic changed the API or it's a bot problem?

**Comment by kem0o** [comment]
it's api problem, the new version of the used lib has problems will work on a fix ASAP

**Comment by Skadro** [comment]
> it's api problem, the new version of the used lib has problems will work on a fix ASAP

Ok. Thank you!

**Comment by innowebka** [comment]
did you fixed it ?

**Comment by oceanman421** [comment]
Did you fixed it? @kem0o
